- hosts: all
  vars:
    - docker_install_compose: true
    - az_devops_agent_role: build
    - az_devops_accountname: "{{ lookup('env', 'azDoAccountName') }}"
    - az_devops_accesstoken: "{{ lookup('env', 'azDoSecretKey') }}"
    - docker_users:
        - az_devops_agent
  roles:
    - gsoft.azure_devops_agent
    - geerlingguy.pip
    - geerlingguy.docker
  tasks:
    - name: Install common packages
      apt:
        pkg:
          - git
          - tar
          - zip
          - gzip
          - openssl
    - name: Reboot agent to apply settings
      reboot:
