- hosts: all
  vars:
    - docker_install_compose: true
    - az_devops_agent_role: build
    - az_devops_accountname: "{{ lookup('env', 'azDoAccountName') }}"
    - az_devops_accesstoken: "{{ lookup('env', 'azDoSecretKey') }}"
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - gsoft.azure_devops_agent
