- hosts: all
  roles:
    - gsoft.azure_devops_agent
  vars:
    - az_devops_agent_role: build
    - az_devops_accountname: "{{ lookup('env', 'azDoAccountName') }}"
    - az_devops_accesstoken: "{{ lookup('env', 'azDoSecretKey') }}"
    